# Generated by Django 4.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commant',
            name='player',
        ),
        migrations.AlterField(
            model_name='match_time',
            name='first_command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match_time',
            name='second_command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='first_command_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='second_command_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='first_command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='second_command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='match',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='commant',
            name='player',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
