# Generated by Django 4.1.7 on 2023-04-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_commant_player_alter_match_time_first_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commant',
            name='player',
        ),
        migrations.AlterField(
            model_name='match_time',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='match_time',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='first_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='media',
            name='second_command_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='first_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames1', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='second_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teames2', to='main.commant'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match_time'),
        ),
        migrations.AddField(
            model_name='commant',
            name='player',
            field=models.ManyToManyField(to='main.player'),
        ),
    ]
