# Generated by Django 4.1.7 on 2023-04-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_commant_player_alter_match_time_first_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commant',
            old_name='player',
            new_name='player_id',
        ),
    ]
