# Generated by Django 4.1.7 on 2023-04-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_player_commant_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_time',
            old_name='first_command',
            new_name='first_command_id',
        ),
        migrations.RenameField(
            model_name='match_time',
            old_name='second_command',
            new_name='second_command_id',
        ),
    ]
